export type Language = 'en' | 'es';

export interface Translations {
  // Navigation
  dashboard: string;
  uploadDocument: string;
  myDocuments: string;
  simplifiedGuides: string;
  legalHistory: string;
  settings: string;
  
  // Authentication
  login: string;
  register: string;
  logout: string;
  email: string;
  password: string;
  confirmPassword: string;
  fullName: string;
  forgotPassword: string;
  createAccount: string;
  signIn: string;
  
  // Dashboard
  hello: string;
  readyToSimplify: string;
  totalDocuments: string;
  processedThisMonth: string;
  successRate: string;
  recentDocuments: string;
  uploadNew: string;
  aiPoweredSimplification: string;
  
  // Upload
  uploadTitle: string;
  uploadSubtitle: string;
  dropDocument: string;
  chooseFile: string;
  supportedFormats: string;
  uploading: string;
  processing: string;
  success: string;
  
  // Summary
  originalDocument: string;
  simplifiedSummary: string;
  generateGuide: string;
  needMoreHelp: string;
  understandingTerms: string;
  
  // Guide
  stepByStepGuide: string;
  stepsCompleted: string;
  allSteps: string;
  completed: string;
  markComplete: string;
  helpfulTips: string;
  previous: string;
  next: string;
  downloadGuide: string;
  exportGuide: string;
  selectLanguage: string;
  preview: string;
  
  // Settings
  language: string;
  darkMode: string;
  lightMode: string;
  deleteAccount: string;
  resetPreferences: string;
  
  // Common
  back: string;
  loading: string;
  error: string;
  tryAgain: string;
  save: string;
  cancel: string;
  close: string;
  
  // Status
  pending: string;
  inProgress: string;
  completed: string;
  failed: string;

  // PDF Export
  exportOptions: string;
  exportLanguage: string;
  generatedBy: string;
  pageOf: string;
  forMoreInfo: string;
  createdOn: string;
  step: string;
  tips: string;
}

const translations: Record<Language, Translations> = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    uploadDocument: 'Upload Document',
    myDocuments: 'My Documents',
    simplifiedGuides: 'Simplified Guides',
    legalHistory: 'Legal History',
    settings: 'Settings',
    
    // Authentication
    login: 'Login',
    register: 'Register',
    logout: 'Sign Out',
    email: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    forgotPassword: 'Forgot your password?',
    createAccount: 'Create an account',
    signIn: 'Sign In',
    
    // Dashboard
    hello: 'Hello',
    readyToSimplify: 'Ready to simplify law today?',
    totalDocuments: 'Total Documents',
    processedThisMonth: 'Processed This Month',
    successRate: 'Success Rate',
    recentDocuments: 'Recent Documents',
    uploadNew: 'Upload New Document',
    aiPoweredSimplification: 'AI-Powered Simplification',
    
    // Upload
    uploadTitle: 'Upload a document and let us simplify it for you',
    uploadSubtitle: 'We\'ll extract the text, translate legal jargon, and guide you through it step by step',
    dropDocument: 'Drop your document here',
    chooseFile: 'Choose File',
    supportedFormats: 'Supported formats: PDF, DOCX (max 10MB)',
    uploading: 'Uploading...',
    processing: 'Processing...',
    success: 'Success!',
    
    // Summary
    originalDocument: 'Original Document',
    simplifiedSummary: 'Simplified Summary',
    generateGuide: 'Generate Step-by-Step Guide',
    needMoreHelp: 'Need More Help?',
    understandingTerms: 'Understanding Legal Terms',
    
    // Guide
    stepByStepGuide: 'Step-by-Step Guide',
    stepsCompleted: 'steps completed',
    allSteps: 'All Steps',
    completed: 'Completed',
    markComplete: 'Mark Complete',
    helpfulTips: 'Helpful Tips',
    previous: 'Previous',
    next: 'Next',
    downloadGuide: 'Download Guide',
    exportGuide: 'Export Guide',
    selectLanguage: 'Select Language',
    preview: 'Preview',
    
    // Settings
    language: 'Language',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    deleteAccount: 'Delete Account',
    resetPreferences: 'Reset Preferences',
    
    // Common
    back: 'Back',
    loading: 'Loading',
    error: 'Error',
    tryAgain: 'Try Again',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    
    // Status
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    failed: 'Failed',

    // PDF Export
    exportOptions: 'Export Options',
    exportLanguage: 'Export Language',
    generatedBy: 'Generated by JustGuide',
    pageOf: 'Page',
    forMoreInfo: 'For more information, visit justguide.com',
    createdOn: 'Created on',
    step: 'Step',
    tips: 'Tips'
  },
  es: {
    // Navigation
    dashboard: 'Panel Principal',
    uploadDocument: 'Subir Documento',
    myDocuments: 'Mis Documentos',
    simplifiedGuides: 'Guías Simplificadas',
    legalHistory: 'Historial Legal',
    settings: 'Configuración',
    
    // Authentication
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    fullName: 'Nombre Completo',
    forgotPassword: '¿Olvidaste tu contraseña?',
    createAccount: 'Crear una cuenta',
    signIn: 'Iniciar Sesión',
    
    // Dashboard
    hello: 'Hola',
    readyToSimplify: '¿Listo para simplificar la ley hoy?',
    totalDocuments: 'Documentos Totales',
    processedThisMonth: 'Procesados Este Mes',
    successRate: 'Tasa de Éxito',
    recentDocuments: 'Documentos Recientes',
    uploadNew: 'Subir Nuevo Documento',
    aiPoweredSimplification: 'Simplificación con IA',
    
    // Upload
    uploadTitle: 'Sube un documento y déjanos simplificarlo para ti',
    uploadSubtitle: 'Extraeremos el texto, traduciremos la jerga legal y te guiaremos paso a paso',
    dropDocument: 'Arrastra tu documento aquí',
    chooseFile: 'Elegir Archivo',
    supportedFormats: 'Formatos soportados: PDF, DOCX (máx 10MB)',
    uploading: 'Subiendo...',
    processing: 'Procesando...',
    success: '¡Éxito!',
    
    // Summary
    originalDocument: 'Documento Original',
    simplifiedSummary: 'Resumen Simplificado',
    generateGuide: 'Generar Guía Paso a Paso',
    needMoreHelp: '¿Necesitas Más Ayuda?',
    understandingTerms: 'Entendiendo Términos Legales',
    
    // Guide
    stepByStepGuide: 'Guía Paso a Paso',
    stepsCompleted: 'pasos completados',
    allSteps: 'Todos los Pasos',
    completed: 'Completado',
    markComplete: 'Marcar Completo',
    helpfulTips: 'Consejos Útiles',
    previous: 'Anterior',
    next: 'Siguiente',
    downloadGuide: 'Descargar Guía',
    exportGuide: 'Exportar Guía',
    selectLanguage: 'Seleccionar Idioma',
    preview: 'Vista Previa',
    
    // Settings
    language: 'Idioma',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    deleteAccount: 'Eliminar Cuenta',
    resetPreferences: 'Restablecer Preferencias',
    
    // Common
    back: 'Atrás',
    loading: 'Cargando',
    error: 'Error',
    tryAgain: 'Intentar de Nuevo',
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    
    // Status
    pending: 'Pendiente',
    inProgress: 'En Progreso',
    completed: 'Completado',
    failed: 'Fallido',

    // PDF Export
    exportOptions: 'Opciones de Exportación',
    exportLanguage: 'Idioma de Exportación',
    generatedBy: 'Generado por JustGuide',
    pageOf: 'Página',
    forMoreInfo: 'Para más información, visita justguide.com',
    createdOn: 'Creado el',
    step: 'Paso',
    tips: 'Consejos'
  }
};

export const languageNames: Record<Language, string> = {
  en: 'English',
  es: 'Español'
};

export const getTranslations = (language: Language): Translations => {
  return translations[language];
};

export const getLanguageFromStorage = (): Language => {
  const stored = localStorage.getItem('justguide-language');
  return (stored === 'es' || stored === 'en') ? stored : 'en';
};

export const setLanguageInStorage = (language: Language): void => {
  localStorage.setItem('justguide-language', language);
};

export const isRTL = (language: Language): boolean => {
  return false; // Neither Spanish nor English are RTL
};