export type Language = 'en' | 'es' | 'fr' | 'pt' | 'de' | 'ar' | 'zh' | 'hi';

export interface Translations {
  // Navigation
  dashboard: string;
  uploadDocument: string;
  myDocuments: string;
  simplifiedGuides: string;
  legalHistory: string;
  settings: string;
  
  // Authentication
  login: string;
  register: string;
  logout: string;
  email: string;
  password: string;
  confirmPassword: string;
  fullName: string;
  forgotPassword: string;
  createAccount: string;
  signIn: string;
  
  // Dashboard
  hello: string;
  readyToSimplify: string;
  totalDocuments: string;
  processedThisMonth: string;
  successRate: string;
  recentDocuments: string;
  uploadNew: string;
  aiPoweredSimplification: string;
  
  // Upload
  uploadTitle: string;
  uploadSubtitle: string;
  dropDocument: string;
  chooseFile: string;
  supportedFormats: string;
  uploading: string;
  processing: string;
  success: string;
  
  // Summary
  originalDocument: string;
  simplifiedSummary: string;
  generateGuide: string;
  needMoreHelp: string;
  understandingTerms: string;
  
  // Guide
  stepByStepGuide: string;
  stepsCompleted: string;
  allSteps: string;
  completed: string;
  markComplete: string;
  helpfulTips: string;
  previous: string;
  next: string;
  downloadGuide: string;
  exportGuide: string;
  selectLanguage: string;
  preview: string;
  
  // Settings
  language: string;
  darkMode: string;
  lightMode: string;
  deleteAccount: string;
  resetPreferences: string;
  
  // Common
  back: string;
  loading: string;
  error: string;
  tryAgain: string;
  save: string;
  cancel: string;
  close: string;
  
  // Status
  pending: string;
  inProgress: string;
  completed: string;
  failed: string;

  // PDF Export
  exportOptions: string;
  exportLanguage: string;
  generatedBy: string;
  pageOf: string;
  forMoreInfo: string;
  createdOn: string;
  step: string;
  tips: string;
}

const translations: Record<Language, Translations> = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    uploadDocument: 'Upload Document',
    myDocuments: 'My Documents',
    simplifiedGuides: 'Simplified Guides',
    legalHistory: 'Legal History',
    settings: 'Settings',
    
    // Authentication
    login: 'Login',
    register: 'Register',
    logout: 'Sign Out',
    email: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    forgotPassword: 'Forgot your password?',
    createAccount: 'Create an account',
    signIn: 'Sign In',
    
    // Dashboard
    hello: 'Hello',
    readyToSimplify: 'Ready to simplify law today?',
    totalDocuments: 'Total Documents',
    processedThisMonth: 'Processed This Month',
    successRate: 'Success Rate',
    recentDocuments: 'Recent Documents',
    uploadNew: 'Upload New Document',
    aiPoweredSimplification: 'AI-Powered Simplification',
    
    // Upload
    uploadTitle: 'Upload a document and let us simplify it for you',
    uploadSubtitle: 'We\'ll extract the text, translate legal jargon, and guide you through it step by step',
    dropDocument: 'Drop your document here',
    chooseFile: 'Choose File',
    supportedFormats: 'Supported formats: PDF, DOCX, JPG, PNG, GIF (max 10MB)',
    uploading: 'Uploading...',
    processing: 'Processing...',
    success: 'Success!',
    
    // Summary
    originalDocument: 'Original Document',
    simplifiedSummary: 'Simplified Summary',
    generateGuide: 'Generate Step-by-Step Guide',
    needMoreHelp: 'Need More Help?',
    understandingTerms: 'Understanding Legal Terms',
    
    // Guide
    stepByStepGuide: 'Step-by-Step Guide',
    stepsCompleted: 'steps completed',
    allSteps: 'All Steps',
    completed: 'Completed',
    markComplete: 'Mark Complete',
    helpfulTips: 'Helpful Tips',
    previous: 'Previous',
    next: 'Next',
    downloadGuide: 'Download Guide',
    exportGuide: 'Export Guide',
    selectLanguage: 'Select Language',
    preview: 'Preview',
    
    // Settings
    language: 'Language',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    deleteAccount: 'Delete Account',
    resetPreferences: 'Reset Preferences',
    
    // Common
    back: 'Back',
    loading: 'Loading',
    error: 'Error',
    tryAgain: 'Try Again',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    
    // Status
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    failed: 'Failed',

    // PDF Export
    exportOptions: 'Export Options',
    exportLanguage: 'Export Language',
    generatedBy: 'Generated by JustGuide',
    pageOf: 'Page',
    forMoreInfo: 'For more information, visit justguide.com',
    createdOn: 'Created on',
    step: 'Step',
    tips: 'Tips'
  },
  es: {
    // Navigation
    dashboard: 'Panel Principal',
    uploadDocument: 'Subir Documento',
    myDocuments: 'Mis Documentos',
    simplifiedGuides: 'Guías Simplificadas',
    legalHistory: 'Historial Legal',
    settings: 'Configuración',
    
    // Authentication
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    fullName: 'Nombre Completo',
    forgotPassword: '¿Olvidaste tu contraseña?',
    createAccount: 'Crear una cuenta',
    signIn: 'Iniciar Sesión',
    
    // Dashboard
    hello: 'Hola',
    readyToSimplify: '¿Listo para simplificar la ley hoy?',
    totalDocuments: 'Documentos Totales',
    processedThisMonth: 'Procesados Este Mes',
    successRate: 'Tasa de Éxito',
    recentDocuments: 'Documentos Recientes',
    uploadNew: 'Subir Nuevo Documento',
    aiPoweredSimplification: 'Simplificación con IA',
    
    // Upload
    uploadTitle: 'Sube un documento y déjanos simplificarlo para ti',
    uploadSubtitle: 'Extraeremos el texto, traduciremos la jerga legal y te guiaremos paso a paso',
    dropDocument: 'Arrastra tu documento aquí',
    chooseFile: 'Elegir Archivo',
    supportedFormats: 'Formatos soportados: PDF, DOCX, JPG, PNG, GIF (máx 10MB)',
    uploading: 'Subiendo...',
    processing: 'Procesando...',
    success: '¡Éxito!',
    
    // Summary
    originalDocument: 'Documento Original',
    simplifiedSummary: 'Resumen Simplificado',
    generateGuide: 'Generar Guía Paso a Paso',
    needMoreHelp: '¿Necesitas Más Ayuda?',
    understandingTerms: 'Entendiendo Términos Legales',
    
    // Guide
    stepByStepGuide: 'Guía Paso a Paso',
    stepsCompleted: 'pasos completados',
    allSteps: 'Todos los Pasos',
    completed: 'Completado',
    markComplete: 'Marcar Completo',
    helpfulTips: 'Consejos Útiles',
    previous: 'Anterior',
    next: 'Siguiente',
    downloadGuide: 'Descargar Guía',
    exportGuide: 'Exportar Guía',
    selectLanguage: 'Seleccionar Idioma',
    preview: 'Vista Previa',
    
    // Settings
    language: 'Idioma',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    deleteAccount: 'Eliminar Cuenta',
    resetPreferences: 'Restablecer Preferencias',
    
    // Common
    back: 'Atrás',
    loading: 'Cargando',
    error: 'Error',
    tryAgain: 'Intentar de Nuevo',
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    
    // Status
    pending: 'Pendiente',
    inProgress: 'En Progreso',
    completed: 'Completado',
    failed: 'Fallido',

    // PDF Export
    exportOptions: 'Opciones de Exportación',
    exportLanguage: 'Idioma de Exportación',
    generatedBy: 'Generado por JustGuide',
    pageOf: 'Página',
    forMoreInfo: 'Para más información, visita justguide.com',
    createdOn: 'Creado el',
    step: 'Paso',
    tips: 'Consejos'
  },
  fr: {
    // Navigation
    dashboard: 'Tableau de Bord',
    uploadDocument: 'Télécharger Document',
    myDocuments: 'Mes Documents',
    simplifiedGuides: 'Guides Simplifiés',
    legalHistory: 'Historique Juridique',
    settings: 'Paramètres',
    
    // Authentication
    login: 'Connexion',
    register: 'S\'inscrire',
    logout: 'Se Déconnecter',
    email: 'Adresse Email',
    password: 'Mot de Passe',
    confirmPassword: 'Confirmer le Mot de Passe',
    fullName: 'Nom Complet',
    forgotPassword: 'Mot de passe oublié?',
    createAccount: 'Créer un compte',
    signIn: 'Se Connecter',
    
    // Dashboard
    hello: 'Bonjour',
    readyToSimplify: 'Prêt à simplifier le droit aujourd\'hui?',
    totalDocuments: 'Documents Totaux',
    processedThisMonth: 'Traités Ce Mois',
    successRate: 'Taux de Réussite',
    recentDocuments: 'Documents Récents',
    uploadNew: 'Télécharger Nouveau Document',
    aiPoweredSimplification: 'Simplification par IA',
    
    // Upload
    uploadTitle: 'Téléchargez un document et laissez-nous le simplifier pour vous',
    uploadSubtitle: 'Nous extrairons le texte, traduirons le jargon juridique et vous guiderons étape par étape',
    dropDocument: 'Déposez votre document ici',
    chooseFile: 'Choisir un Fichier',
    supportedFormats: 'Formats supportés: PDF, DOCX, JPG, PNG, GIF (max 10MB)',
    uploading: 'Téléchargement...',
    processing: 'Traitement...',
    success: 'Succès!',
    
    // Summary
    originalDocument: 'Document Original',
    simplifiedSummary: 'Résumé Simplifié',
    generateGuide: 'Générer Guide Étape par Étape',
    needMoreHelp: 'Besoin d\'Aide?',
    understandingTerms: 'Comprendre les Termes Juridiques',
    
    // Guide
    stepByStepGuide: 'Guide Étape par Étape',
    stepsCompleted: 'étapes terminées',
    allSteps: 'Toutes les Étapes',
    completed: 'Terminé',
    markComplete: 'Marquer Terminé',
    helpfulTips: 'Conseils Utiles',
    previous: 'Précédent',
    next: 'Suivant',
    downloadGuide: 'Télécharger Guide',
    exportGuide: 'Exporter Guide',
    selectLanguage: 'Sélectionner Langue',
    preview: 'Aperçu',
    
    // Settings
    language: 'Langue',
    darkMode: 'Mode Sombre',
    lightMode: 'Mode Clair',
    deleteAccount: 'Supprimer Compte',
    resetPreferences: 'Réinitialiser Préférences',
    
    // Common
    back: 'Retour',
    loading: 'Chargement',
    error: 'Erreur',
    tryAgain: 'Réessayer',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    close: 'Fermer',
    
    // Status
    pending: 'En Attente',
    inProgress: 'En Cours',
    completed: 'Terminé',
    failed: 'Échoué',

    // PDF Export
    exportOptions: 'Options d\'Exportation',
    exportLanguage: 'Langue d\'Exportation',
    generatedBy: 'Généré par JustGuide',
    pageOf: 'Page',
    forMoreInfo: 'Pour plus d\'informations, visitez justguide.com',
    createdOn: 'Créé le',
    step: 'Étape',
    tips: 'Conseils'
  },
  pt: {
    // Navigation
    dashboard: 'Painel',
    uploadDocument: 'Enviar Documento',
    myDocuments: 'Meus Documentos',
    simplifiedGuides: 'Guias Simplificados',
    legalHistory: 'Histórico Legal',
    settings: 'Configurações',
    
    // Authentication
    login: 'Entrar',
    register: 'Registrar',
    logout: 'Sair',
    email: 'Endereço de Email',
    password: 'Senha',
    confirmPassword: 'Confirmar Senha',
    fullName: 'Nome Completo',
    forgotPassword: 'Esqueceu sua senha?',
    createAccount: 'Criar uma conta',
    signIn: 'Entrar',
    
    // Dashboard
    hello: 'Olá',
    readyToSimplify: 'Pronto para simplificar a lei hoje?',
    totalDocuments: 'Documentos Totais',
    processedThisMonth: 'Processados Este Mês',
    successRate: 'Taxa de Sucesso',
    recentDocuments: 'Documentos Recentes',
    uploadNew: 'Enviar Novo Documento',
    aiPoweredSimplification: 'Simplificação por IA',
    
    // Upload
    uploadTitle: 'Envie um documento e deixe-nos simplificá-lo para você',
    uploadSubtitle: 'Extrairemos o texto, traduziremos o jargão jurídico e o guiaremos passo a passo',
    dropDocument: 'Solte seu documento aqui',
    chooseFile: 'Escolher Arquivo',
    supportedFormats: 'Formatos suportados: PDF, DOCX, JPG, PNG, GIF (máx 10MB)',
    uploading: 'Enviando...',
    processing: 'Processando...',
    success: 'Sucesso!',
    
    // Summary
    originalDocument: 'Documento Original',
    simplifiedSummary: 'Resumo Simplificado',
    generateGuide: 'Gerar Guia Passo a Passo',
    needMoreHelp: 'Precisa de Mais Ajuda?',
    understandingTerms: 'Entendendo Termos Legais',
    
    // Guide
    stepByStepGuide: 'Guia Passo a Passo',
    stepsCompleted: 'passos concluídos',
    allSteps: 'Todos os Passos',
    completed: 'Concluído',
    markComplete: 'Marcar Concluído',
    helpfulTips: 'Dicas Úteis',
    previous: 'Anterior',
    next: 'Próximo',
    downloadGuide: 'Baixar Guia',
    exportGuide: 'Exportar Guia',
    selectLanguage: 'Selecionar Idioma',
    preview: 'Visualizar',
    
    // Settings
    language: 'Idioma',
    darkMode: 'Modo Escuro',
    lightMode: 'Modo Claro',
    deleteAccount: 'Excluir Conta',
    resetPreferences: 'Redefinir Preferências',
    
    // Common
    back: 'Voltar',
    loading: 'Carregando',
    error: 'Erro',
    tryAgain: 'Tentar Novamente',
    save: 'Salvar',
    cancel: 'Cancelar',
    close: 'Fechar',
    
    // Status
    pending: 'Pendente',
    inProgress: 'Em Andamento',
    completed: 'Concluído',
    failed: 'Falhou',

    // PDF Export
    exportOptions: 'Opções de Exportação',
    exportLanguage: 'Idioma de Exportação',
    generatedBy: 'Gerado por JustGuide',
    pageOf: 'Página',
    forMoreInfo: 'Para mais informações, visite justguide.com',
    createdOn: 'Criado em',
    step: 'Passo',
    tips: 'Dicas'
  },
  de: {
    // Navigation
    dashboard: 'Dashboard',
    uploadDocument: 'Dokument Hochladen',
    myDocuments: 'Meine Dokumente',
    simplifiedGuides: 'Vereinfachte Leitfäden',
    legalHistory: 'Rechtsgeschichte',
    settings: 'Einstellungen',
    
    // Authentication
    login: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    email: 'E-Mail-Adresse',
    password: 'Passwort',
    confirmPassword: 'Passwort Bestätigen',
    fullName: 'Vollständiger Name',
    forgotPassword: 'Passwort vergessen?',
    createAccount: 'Konto erstellen',
    signIn: 'Anmelden',
    
    // Dashboard
    hello: 'Hallo',
    readyToSimplify: 'Bereit, das Recht heute zu vereinfachen?',
    totalDocuments: 'Gesamte Dokumente',
    processedThisMonth: 'Diesen Monat Verarbeitet',
    successRate: 'Erfolgsrate',
    recentDocuments: 'Aktuelle Dokumente',
    uploadNew: 'Neues Dokument Hochladen',
    aiPoweredSimplification: 'KI-gestützte Vereinfachung',
    
    // Upload
    uploadTitle: 'Laden Sie ein Dokument hoch und lassen Sie es uns für Sie vereinfachen',
    uploadSubtitle: 'Wir extrahieren den Text, übersetzen Rechtsjargon und führen Sie Schritt für Schritt durch',
    dropDocument: 'Dokument hier ablegen',
    chooseFile: 'Datei Auswählen',
    supportedFormats: 'Unterstützte Formate: PDF, DOCX, JPG, PNG, GIF (max 10MB)',
    uploading: 'Hochladen...',
    processing: 'Verarbeitung...',
    success: 'Erfolg!',
    
    // Summary
    originalDocument: 'Originaldokument',
    simplifiedSummary: 'Vereinfachte Zusammenfassung',
    generateGuide: 'Schritt-für-Schritt-Anleitung Erstellen',
    needMoreHelp: 'Brauchen Sie Mehr Hilfe?',
    understandingTerms: 'Rechtsbegriffe Verstehen',
    
    // Guide
    stepByStepGuide: 'Schritt-für-Schritt-Anleitung',
    stepsCompleted: 'Schritte abgeschlossen',
    allSteps: 'Alle Schritte',
    completed: 'Abgeschlossen',
    markComplete: 'Als Abgeschlossen Markieren',
    helpfulTips: 'Hilfreiche Tipps',
    previous: 'Zurück',
    next: 'Weiter',
    downloadGuide: 'Anleitung Herunterladen',
    exportGuide: 'Anleitung Exportieren',
    selectLanguage: 'Sprache Auswählen',
    preview: 'Vorschau',
    
    // Settings
    language: 'Sprache',
    darkMode: 'Dunkler Modus',
    lightMode: 'Heller Modus',
    deleteAccount: 'Konto Löschen',
    resetPreferences: 'Einstellungen Zurücksetzen',
    
    // Common
    back: 'Zurück',
    loading: 'Laden',
    error: 'Fehler',
    tryAgain: 'Erneut Versuchen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    close: 'Schließen',
    
    // Status
    pending: 'Ausstehend',
    inProgress: 'In Bearbeitung',
    completed: 'Abgeschlossen',
    failed: 'Fehlgeschlagen',

    // PDF Export
    exportOptions: 'Export-Optionen',
    exportLanguage: 'Export-Sprache',
    generatedBy: 'Erstellt von JustGuide',
    pageOf: 'Seite',
    forMoreInfo: 'Für weitere Informationen besuchen Sie justguide.com',
    createdOn: 'Erstellt am',
    step: 'Schritt',
    tips: 'Tipps'
  },
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    uploadDocument: 'رفع وثيقة',
    myDocuments: 'وثائقي',
    simplifiedGuides: 'الأدلة المبسطة',
    legalHistory: 'التاريخ القانوني',
    settings: 'الإعدادات',
    
    // Authentication
    login: 'تسجيل الدخول',
    register: 'التسجيل',
    logout: 'تسجيل الخروج',
    email: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    fullName: 'الاسم الكامل',
    forgotPassword: 'نسيت كلمة المرور؟',
    createAccount: 'إنشاء حساب',
    signIn: 'تسجيل الدخول',
    
    // Dashboard
    hello: 'مرحبا',
    readyToSimplify: 'مستعد لتبسيط القانون اليوم؟',
    totalDocuments: 'إجمالي الوثائق',
    processedThisMonth: 'تمت معالجتها هذا الشهر',
    successRate: 'معدل النجاح',
    recentDocuments: 'الوثائق الحديثة',
    uploadNew: 'رفع وثيقة جديدة',
    aiPoweredSimplification: 'التبسيط بالذكاء الاصطناعي',
    
    // Upload
    uploadTitle: 'ارفع وثيقة ودعنا نبسطها لك',
    uploadSubtitle: 'سنستخرج النص ونترجم المصطلحات القانونية ونرشدك خطوة بخطوة',
    dropDocument: 'اسقط وثيقتك هنا',
    chooseFile: 'اختر ملف',
    supportedFormats: 'الصيغ المدعومة: PDF, DOCX, JPG, PNG, GIF (حد أقصى 10 ميجابايت)',
    uploading: 'جاري الرفع...',
    processing: 'جاري المعالجة...',
    success: 'نجح!',
    
    // Summary
    originalDocument: 'الوثيقة الأصلية',
    simplifiedSummary: 'الملخص المبسط',
    generateGuide: 'إنشاء دليل خطوة بخطوة',
    needMoreHelp: 'تحتاج مساعدة أكثر؟',
    understandingTerms: 'فهم المصطلحات القانونية',
    
    // Guide
    stepByStepGuide: 'دليل خطوة بخطوة',
    stepsCompleted: 'خطوات مكتملة',
    allSteps: 'جميع الخطوات',
    completed: 'مكتمل',
    markComplete: 'وضع علامة مكتمل',
    helpfulTips: 'نصائح مفيدة',
    previous: 'السابق',
    next: 'التالي',
    downloadGuide: 'تحميل الدليل',
    exportGuide: 'تصدير الدليل',
    selectLanguage: 'اختر اللغة',
    preview: 'معاينة',
    
    // Settings
    language: 'اللغة',
    darkMode: 'الوضع المظلم',
    lightMode: 'الوضع الفاتح',
    deleteAccount: 'حذف الحساب',
    resetPreferences: 'إعادة تعيين التفضيلات',
    
    // Common
    back: 'رجوع',
    loading: 'جاري التحميل',
    error: 'خطأ',
    tryAgain: 'حاول مرة أخرى',
    save: 'حفظ',
    cancel: 'إلغاء',
    close: 'إغلاق',
    
    // Status
    pending: 'معلق',
    inProgress: 'قيد التنفيذ',
    completed: 'مكتمل',
    failed: 'فشل',

    // PDF Export
    exportOptions: 'خيارات التصدير',
    exportLanguage: 'لغة التصدير',
    generatedBy: 'تم إنشاؤه بواسطة JustGuide',
    pageOf: 'صفحة',
    forMoreInfo: 'لمزيد من المعلومات، قم بزيارة justguide.com',
    createdOn: 'تم إنشاؤه في',
    step: 'خطوة',
    tips: 'نصائح'
  },
  zh: {
    // Navigation
    dashboard: '仪表板',
    uploadDocument: '上传文档',
    myDocuments: '我的文档',
    simplifiedGuides: '简化指南',
    legalHistory: '法律历史',
    settings: '设置',
    
    // Authentication
    login: '登录',
    register: '注册',
    logout: '退出',
    email: '电子邮件地址',
    password: '密码',
    confirmPassword: '确认密码',
    fullName: '全名',
    forgotPassword: '忘记密码？',
    createAccount: '创建账户',
    signIn: '登录',
    
    // Dashboard
    hello: '你好',
    readyToSimplify: '准备好今天简化法律了吗？',
    totalDocuments: '文档总数',
    processedThisMonth: '本月处理',
    successRate: '成功率',
    recentDocuments: '最近文档',
    uploadNew: '上传新文档',
    aiPoweredSimplification: 'AI驱动的简化',
    
    // Upload
    uploadTitle: '上传文档，让我们为您简化',
    uploadSubtitle: '我们将提取文本，翻译法律术语，并逐步指导您',
    dropDocument: '将文档拖放到这里',
    chooseFile: '选择文件',
    supportedFormats: '支持的格式：PDF、DOCX、JPG、PNG、GIF（最大10MB）',
    uploading: '上传中...',
    processing: '处理中...',
    success: '成功！',
    
    // Summary
    originalDocument: '原始文档',
    simplifiedSummary: '简化摘要',
    generateGuide: '生成逐步指南',
    needMoreHelp: '需要更多帮助？',
    understandingTerms: '理解法律术语',
    
    // Guide
    stepByStepGuide: '逐步指南',
    stepsCompleted: '步骤已完成',
    allSteps: '所有步骤',
    completed: '已完成',
    markComplete: '标记完成',
    helpfulTips: '有用提示',
    previous: '上一个',
    next: '下一个',
    downloadGuide: '下载指南',
    exportGuide: '导出指南',
    selectLanguage: '选择语言',
    preview: '预览',
    
    // Settings
    language: '语言',
    darkMode: '深色模式',
    lightMode: '浅色模式',
    deleteAccount: '删除账户',
    resetPreferences: '重置偏好',
    
    // Common
    back: '返回',
    loading: '加载中',
    error: '错误',
    tryAgain: '重试',
    save: '保存',
    cancel: '取消',
    close: '关闭',
    
    // Status
    pending: '待处理',
    inProgress: '进行中',
    completed: '已完成',
    failed: '失败',

    // PDF Export
    exportOptions: '导出选项',
    exportLanguage: '导出语言',
    generatedBy: '由JustGuide生成',
    pageOf: '页',
    forMoreInfo: '更多信息请访问justguide.com',
    createdOn: '创建于',
    step: '步骤',
    tips: '提示'
  },
  hi: {
    // Navigation
    dashboard: 'डैशबोर्ड',
    uploadDocument: 'दस्तावेज़ अपलोड करें',
    myDocuments: 'मेरे दस्तावेज़',
    simplifiedGuides: 'सरलीकृत गाइड',
    legalHistory: 'कानूनी इतिहास',
    settings: 'सेटिंग्स',
    
    // Authentication
    login: 'लॉगिन',
    register: 'रजिस्टर',
    logout: 'लॉगआउट',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    fullName: 'पूरा नाम',
    forgotPassword: 'पासवर्ड भूल गए?',
    createAccount: 'खाता बनाएं',
    signIn: 'साइन इन',
    
    // Dashboard
    hello: 'नमस्ते',
    readyToSimplify: 'आज कानून को सरल बनाने के लिए तैयार हैं?',
    totalDocuments: 'कुल दस्तावेज़',
    processedThisMonth: 'इस महीने प्रोसेस किए गए',
    successRate: 'सफलता दर',
    recentDocuments: 'हाल के दस्तावेज़',
    uploadNew: 'नया दस्तावेज़ अपलोड करें',
    aiPoweredSimplification: 'AI-संचालित सरलीकरण',
    
    // Upload
    uploadTitle: 'एक दस्तावेज़ अपलोड करें और हमें इसे आपके लिए सरल बनाने दें',
    uploadSubtitle: 'हम टेक्स्ट निकालेंगे, कानूनी शब्दजाल का अनुवाद करेंगे, और आपको चरणबद्ध तरीके से मार्गदर्शन देंगे',
    dropDocument: 'अपना दस्तावेज़ यहाँ छोड़ें',
    chooseFile: 'फ़ाइल चुनें',
    supportedFormats: 'समर्थित प्रारूप: PDF, DOCX, JPG, PNG, GIF (अधिकतम 10MB)',
    uploading: 'अपलोड हो रहा है...',
    processing: 'प्रोसेसिंग...',
    success: 'सफल!',
    
    // Summary
    originalDocument: 'मूल दस्तावेज़',
    simplifiedSummary: 'सरलीकृत सारांश',
    generateGuide: 'चरणबद्ध गाइड बनाएं',
    needMoreHelp: 'और मदद चाहिए?',
    understandingTerms: 'कानूनी शब्दों को समझना',
    
    // Guide
    stepByStepGuide: 'चरणबद्ध गाइड',
    stepsCompleted: 'चरण पूरे हुए',
    allSteps: 'सभी चरण',
    completed: 'पूर्ण',
    markComplete: 'पूर्ण के रूप में चिह्नित करें',
    helpfulTips: 'उपयोगी सुझाव',
    previous: 'पिछला',
    next: 'अगला',
    downloadGuide: 'गाइड डाउनलोड करें',
    exportGuide: 'गाइड निर्यात करें',
    selectLanguage: 'भाषा चुनें',
    preview: 'पूर्वावलोकन',
    
    // Settings
    language: 'भाषा',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    deleteAccount: 'खाता हटाएं',
    resetPreferences: 'प्राथमिकताएं रीसेट करें',
    
    // Common
    back: 'वापस',
    loading: 'लोड हो रहा है',
    error: 'त्रुटि',
    tryAgain: 'फिर कोशिश करें',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    close: 'बंद करें',
    
    // Status
    pending: 'लंबित',
    inProgress: 'प्रगति में',
    completed: 'पूर्ण',
    failed: 'असफल',

    // PDF Export
    exportOptions: 'निर्यात विकल्प',
    exportLanguage: 'निर्यात भाषा',
    generatedBy: 'JustGuide द्वारा जेनरेट किया गया',
    pageOf: 'पृष्ठ',
    forMoreInfo: 'अधिक जानकारी के लिए, justguide.com पर जाएं',
    createdOn: 'बनाया गया',
    step: 'चरण',
    tips: 'सुझाव'
  }
};

export const languageNames: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  pt: 'Português',
  de: 'Deutsch',
  ar: 'العربية',
  zh: '中文',
  hi: 'हिन्दी'
};

export const getTranslations = (language: Language): Translations => {
  return translations[language];
};

export const getLanguageFromStorage = (): Language => {
  const stored = localStorage.getItem('justguide-language');
  return (stored && Object.keys(languageNames).includes(stored)) ? stored as Language : 'en';
};

export const setLanguageInStorage = (language: Language): void => {
  localStorage.setItem('justguide-language', language);
};

export const isRTL = (language: Language): boolean => {
  return language === 'ar';
};